user:
  url: http://user:5001
submission:
  url: http://submission:5003 #database container name
management:
  url: http://management:5002

server:
  port: 8070

eureka:
  instance:
    hostname: eureka-reg
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-reg:8070/eureka/


spring:
  application:
    name: "eurekaserver"
