user:
  url: http://user:5001
submission:
  url: http://submission:5003
management:
  url: http://management:5002

server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE
  datasource:
    url: jdbc:mysql://taskmanager.c5666k00u2dc.ap-south-1.rds.amazonaws.com:3306/taskmanager
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-reg:8070/eureka/
